[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "alog_system"
  omit_hostname = false

# --- КУДА ОТПРАВЛЯТЬ (InfluxDB) ---
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_ADMIN_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"

# --- ОТКУДА ПРИНИМАТЬ (UDP порт 5000) ---
[[inputs.socket_listener]]
  service_address = "udp://:5000"
  
  # Настройки парсера данных
  data_format = "csv"
  csv_delimiter = ";"
  name_override = "power_monitor"
  
  # Структура CSV строки
  csv_column_names = [
    "timestamp", 
    "voltage", "voltage_err", 
    "current", "current_err", 
    "power", 
    "relay1", "relay2"
  ]
  
  # Типы данных для колонок
  csv_column_types = ["string", "float", "int", "float", "int", "float", "int", "int"]
  
  # Игнорируем timestamp из CSV и используем текущее время Telegraf
  # csv_skip_rows = 0
  
  # Используем timestamp из CSV как метку времени
  csv_timestamp_column = "timestamp"
  csv_timestamp_format = "unix"
