[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Viewer

[dashboards]
# Дашборд загружается автоматически через provisioning
# default_home_dashboard_path = /var/lib/grafana/dashboards/alog_dashboard.json
